@baseUrl = http://localhost:3001
@email = admin@example.com
@password = password

### User Authentication Actions

#### User Registration
# @name registerUser
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "user": {
    "email": "{{email}}",
    "password": "{{password}}",
    "password_confirmation": "{{password}}",
    "admin": true
  }
}

#### User Login
# @name loginUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

#### User Logout
# @name logoutUser
DELETE {{baseUrl}}/auth/logout

###