@baseUrl = http://localhost:3000
@email = "test6@example.com"
@password = "password"

### Sign Up (Devise User Creation)
# @name signUp
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}},
  "password_confirmation": {{password}},
  "confirm_success_url": "YOUR_FRONT_END_URL"
}

###

### Sign In (Devise User Session Creation)
# @name signIn
POST {{baseUrl}}/auth/sign_in
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}}
}

###

# Set user details from signIn response
@Authorization = {{signIn.response.headers.Authorization}}
@uid = {{signIn.response.headers.uid}}
@client = {{signIn.response.headers.client}}
@expiry = {{signIn.response.headers.expiry}}

### List Todos 
GET {{baseUrl}}/todos
Authorization: {{Authorization}}
uid: {{uid}}
client: {{client}}
expiry: {{expiry}}

###

### Create a New Todo 
POST {{baseUrl}}/todos
Authorization: {{Authorization}}
uid: {{uid}}
client: {{client}}
expiry: {{expiry}}
Content-Type: application/json
{
  "title": "New Todo Item"
}

###
